import mongoose, { Schema, Document } from 'mongoose';

export interface IVideo extends Document {
  title: string;
  description: string;
  courseId?: mongoose.Types.ObjectId;
  lessonId?: mongoose.Types.ObjectId;
  uploadedBy: mongoose.Types.ObjectId;
  originalFile: {
    filename: string;
    size: number;
    mimetype: string;
    url: string;
    duration: number;
  };
  processedFiles: {
    resolution: string;
    url: string;
    size: number;
    bitrate: number;
    codec: string;
  }[];
  thumbnail: {
    url: string;
    timestamps: number[];
  };
  hlsManifest?: string;
  dashManifest?: string;
  subtitles: {
    language: string;
    url: string;
    autoGenerated: boolean;
  }[];
  chapters: {
    title: string;
    timestamp: number;
    description?: string;
  }[];
  watermark?: {
    enabled: boolean;
    text?: string;
    imageUrl?: string;
    position: 'top-left' | 'top-right' | 'bottom-left' | 'bottom-right' | 'center';
    opacity: number;
  };
  drm?: {
    enabled: boolean;
    provider: string;
    keyId?: string;
    contentId?: string;
  };
  status: 'uploading' | 'processing' | 'ready' | 'error';
  processingProgress: number;
  errorMessage?: string;
  analytics: {
    views: number;
    totalWatchTime: number;
    averageWatchTime: number;
    completionRate: number;
    engagementScore: number;
  };
  metadata: {
    width: number;
    height: number;
    aspectRatio: string;
    fps: number;
    codec: string;
    bitrate: number;
  };
  isPremium: boolean;
  isPublished: boolean;
  publishedAt?: Date;
  cdnUrl?: string;
  tags: string[];
  category: string;
  createdAt: Date;
  updatedAt: Date;
}

const VideoSchema: Schema = new Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
      maxlength: 200,
    },
    description: {
      type: String,
      trim: true,
      maxlength: 2000,
    },
    courseId: {
      type: Schema.Types.ObjectId,
      ref: 'Course',
    },
    lessonId: {
      type: Schema.Types.ObjectId,
      ref: 'Lesson',
    },
    uploadedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    originalFile: {
      filename: { type: String, required: true },
      size: { type: Number, required: true },
      mimetype: { type: String, required: true },
      url: { type: String, required: true },
      duration: { type: Number, required: true },
    },
    processedFiles: [
      {
        resolution: { type: String, required: true },
        url: { type: String, required: true },
        size: { type: Number, required: true },
        bitrate: { type: Number, required: true },
        codec: { type: String, required: true },
      },
    ],
    thumbnail: {
      url: { type: String },
      timestamps: [{ type: Number }],
    },
    hlsManifest: {
      type: String,
    },
    dashManifest: {
      type: String,
    },
    subtitles: [
      {
        language: { type: String, required: true },
        url: { type: String, required: true },
        autoGenerated: { type: Boolean, default: false },
      },
    ],
    chapters: [
      {
        title: { type: String, required: true },
        timestamp: { type: Number, required: true },
        description: { type: String },
      },
    ],
    watermark: {
      enabled: { type: Boolean, default: false },
      text: { type: String },
      imageUrl: { type: String },
      position: {
        type: String,
        enum: ['top-left', 'top-right', 'bottom-left', 'bottom-right', 'center'],
        default: 'bottom-right',
      },
      opacity: { type: Number, default: 0.7, min: 0, max: 1 },
    },
    drm: {
      enabled: { type: Boolean, default: false },
      provider: { type: String, enum: ['widevine', 'fairplay', 'playready'] },
      keyId: { type: String },
      contentId: { type: String },
    },
    status: {
      type: String,
      enum: ['uploading', 'processing', 'ready', 'error'],
      default: 'uploading',
    },
    processingProgress: {
      type: Number,
      default: 0,
      min: 0,
      max: 100,
    },
    errorMessage: {
      type: String,
    },
    analytics: {
      views: { type: Number, default: 0 },
      totalWatchTime: { type: Number, default: 0 },
      averageWatchTime: { type: Number, default: 0 },
      completionRate: { type: Number, default: 0 },
      engagementScore: { type: Number, default: 0 },
    },
    metadata: {
      width: { type: Number },
      height: { type: Number },
      aspectRatio: { type: String },
      fps: { type: Number },
      codec: { type: String },
      bitrate: { type: Number },
    },
    isPremium: {
      type: Boolean,
      default: false,
    },
    isPublished: {
      type: Boolean,
      default: false,
    },
    publishedAt: {
      type: Date,
    },
    cdnUrl: {
      type: String,
    },
    tags: [
      {
        type: String,
        trim: true,
      },
    ],
    category: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// Indexes for better query performance
VideoSchema.index({ courseId: 1, lessonId: 1 });
VideoSchema.index({ uploadedBy: 1 });
VideoSchema.index({ status: 1 });
VideoSchema.index({ isPublished: 1, publishedAt: -1 });
VideoSchema.index({ tags: 1 });
VideoSchema.index({ 'analytics.views': -1 });

export default mongoose.model<IVideo>('Video', VideoSchema);
